sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20020822

  alioss:
    bucket-name: web-cnan-sky
    endpoint: https://oss-cn-beijing.aliyuncs.com
    region: cn-beijing

  redis:
    host: localhost
    port: 6379
    password: 123456
  wechat:
    appid: wx766430b5146ef7be
    secret: 10d8e8a0454142309610b4e7f7252261